---
- name: "AWS - Install docker"
  hosts: all
  become: yes
  tasks:
    - name: Update all packages
      yum:
        name: '*'
        state: latest
        update_only: yes

    - name: Install epel (centos) via amazon-linux-extras packages
      shell: "sudo amazon-linux-extras install epel -y"

    - name: Install docker-ce (centos) via amazon-linux-extras packages
      shell: "amazon-linux-extras install docker=18.06.1 -y"

    - name: Enable Docker CE service at startup
      service:
        name: docker
        state: started
        enabled: yes

    - name: Ensure a list of yum packages are installed
      yum:
        name: "{{ packages }}"
        state: present        
      vars:
        packages: python3-pip        

    - name: Upgrade pip
      shell: "python3 -m pip install --user --upgrade pip"     

    - name: Install docker-compose
      shell: "python3 -m pip install docker-compose"      

    - name: Clone a repo with separate git directory
      git:
        repo: https://github.com/nick1846/docker.git 
        dest: /home/ec2-user/docker
      
    - name: deploy Docker Compose app
      shell: 
        chdir: /home/ec2-user/docker/docker-compose
        cmd: "docker-compose up -d"
        
        
    
    
