---
- hosts: all
  become: true
  tasks: 
    - name: Updating yum packages 
      yum:
<<<<<<< HEAD
     
        
=======
        name: "*"
        state: latest 
        update_only: yes
>>>>>>> 2b847c8d76e7e9e4a4052e399e5a4def1fda5522
